services:
  my_web:
    user: ${MY_UID}:${MY_GID}
    build:
      context: ./build
      dockerfile: Dockerfile.php
      args:
        UID: ${MY_UID}
        GID: ${MY_GID}      
    ports:
      - 8080:80
    volumes:
      - "./php:/var/www/html"

  my_mariadb:
    user: ${MY_UID}:${MY_GID}
    build:
      context: ./build
      dockerfile: Dockerfile.mariadb
      args:
        UID: ${MY_UID}
        GID: ${MY_GID}
    environment:
      - MARIADB_ROOT_PASSWORD=ciccio
      - MARIADB_DATABASE=my_app
    volumes:
      - "./mysql:/var/lib/mysql"
      - "./build/init.sql:/docker-entrypoint-initdb.d/init.sql"

  my_phpMyAdmin:
    image: phpmyadmin
    ports:
      - 8081:80
    environment:
      - PMA_HOST=my_mariadb

  my_node:
    user: ${MY_UID}:${MY_GID}
    build:
      context: ./build
      dockerfile: Dockerfile.node
      args:
        UID: ${MY_UID}
        GID: ${MY_GID}
    ports:
      - 3000:3000
    volumes:
      - "./app:/app"

